### ISSUE TITLE
Update runtime to 19.08

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/net.pcsx2.PCSX2#18]

**Comment by Pixelnarium** [comment]
Is there still i386 support for the 19.08 runtime?

```
$ flatpak install org.freedesktop.Sdk/i386/19.08
Looking for matches…
error: No remote refs found similar to ‘org.freedesktop.Sdk/i386/19.08’
```

**Comment by TingPing** [comment]
We need to switch to the x86_64 runtime and use multiarch support inside of that.

**Comment by Pixelnarium** [comment]
That's unfortunate. Having a 32bit runtime was a nice solution for older apps since it prevents cross-compiling stuff. Since searching for "org.freedesktop.Sdk.Compat.i386" results in near to nothing I guess there is no documentation for it? I guess the shared-modules repo is also unusable that way?

**Comment by TingPing** [comment]
I've not looked into so I simply don't know.

I do number of actual i386 users was near 0.

**Comment by Pixelnarium** [comment]
Please have a look at my PR.
