### ISSUE TITLE
“failed to read/write nvm/mec file”

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/net.pcsx2.PCSX2#22]
This error occurs on Endless OS

![Captura de tela de 2020-05-08 20-10-09](https://user-images.githubusercontent.com/26097419/81456261-1305e080-9168-11ea-88d8-f531172c75db.png)

**Comment by LeandroStanger** [comment]
**CC:** @TingPing @barthalion

**Comment by TingPing** [comment]
Stop spamming people with pings.

For legal reasons the BIOS isn't distributed, that is your problem to solve as a user.

**Comment by TingPing** [comment]
I will add the files are placed in `~/.var/app/net.pcsx2.PCSX2/config/PCSX2/bios`

**Comment by pvaret** [comment]
To anyone else who stumbled upon this and are still confused:

The problem is that the PCSX2 flatpak requires _write_ access to the BIOS directory. But flatpak locks access down very tightly by default, and there is no way to point PCSX2 to a different directory for its writes. So, whichever directory where you have extracted the BIOS from your legitimately purchased PS2 may not work: the BIOS files have got to be specifically the directory that @TingPing pointed to in [this comment](/flathub/net.pcsx2.PCSX2/issues/22#issuecomment-626234880).

**Comment by refi64** [comment]
Would there be any objection to adding write access to at least xdg-downloads? That's a pretty common location for the BIOS files and would help improve the initial UX a bit without too much sandboxing tradeoff.
